feat(docs): Docs for handling line ending errors during installation
metabrainz/bookbrainz-dev-docs pull request #12
Opened 2023-03-03 03:40 UTC by jonkaonor

Added documentation in the Troubleshooting section for how to fix errors occurring in the bookbrainz-site installation process caused by Linux line endings being replaced by Windows line endings in certain script files.

2023-03-04 13:36 UTC, jonkaonor commented
Sorry I just realized you were asking for me to write this documentation on the installation-troubleshooting document in the bookbrainz-site repository and not this one.  I'll add the documentation to that shortly, feel free to close this request if this isn't the proper place for it.

2023-03-04 13:46 UTC, kellnerd commented
I think you've submitted this PR in the right place, the plan is to move the docs from bookbrainz-site into this repo: https://github.com/metabrainz/bookbrainz-dev-docs/pull/11#issuecomment-1400173944

2023-03-04 14:06 UTC, jonkaonor commented
Ah okay I read through the comments and understand now. Thank you for the clarification kellnerd.

2023-03-13 11:17 UTC, MonkeyDo requested changes
Thanks for adding this troubleshooting !

Indeed this is the right place for this PR :)

2023-03-13 11:17 UTC, MonkeyDo commented on docs/troubleshooting.rst
> +     git clone --recurse-submodules https://github.com/metabrainz/bookbrainz-site.git
I think here we should just point to the relevant section in the docs.
The main reason is that when we copy instructions in multiple places it is easier to forget to modify all of them.
As a great example, we don't use submodules anymore so the `--recurse-submodules` flag hasn't been needed for a couple of years, and we forgot to update it everywhere :p

So I think we should have something like this:
```suggestion
  3. Clone the bookbrainz repository again using the appropriate command. Follow the instructions here: :ref:`cloning-repository`
```

Which requires adding this line above the "Cloning" header in [installation.rst](https://github.com/metabrainz/bookbrainz-dev-docs/blob/master/docs/installation.rst#cloning) (and an emtpty line in-between) to be able to reference it:
```
.. _cloning-repository:

Cloning
*******
```

2023-03-13 11:17 UTC, MonkeyDo commented on docs/troubleshooting.rst
> +  ::
This `::` is used to present a block of code or a command, and is not required here
```suggestion

```

2023-03-13 11:17 UTC, MonkeyDo commented on docs/troubleshooting.rst
> +  ::
Same as number 2.
```suggestion

```

2024-01-24 10:24 UTC, MonkeyDo approved these changes
Took the liberty of finishing off this PR

2024-01-24 10:25 UTC, merged