update forking and cloning instruction
metabrainz/bookbrainz-dev-docs pull request #15
Opened 2023-03-07 12:16 UTC by Vivekumar08

2023-03-07 13:00 UTC, MonkeyDo requested changes
Thanks, that makes more sense to new users ! :)

2023-03-07 13:00 UTC, MonkeyDo commented on docs/installation.rst
> +    git clone --recurse-submodules https://github.com/<Your_Github_Username>/bookbrainz-site.git
Actually, while we are here, I notice we still have submodules instructions while not using submodules anymore
```suggestion
    git clone https://github.com/<Your_Github_Username>/bookbrainz-site.git
```

2023-03-09 02:01 UTC, Vivekumar08 commented
Are there any changes that are required to do in the installation guide?

2023-03-13 10:26 UTC, MonkeyDo approved these changes

2023-03-13 10:26 UTC, merged